# This file is covered by the LICENSE file in the root of this project.
# Developed by: Xieyuanli Chen
# Configuration for preparing residual images (specifying all the paths)
# --------------------------------------------------------------------

# General parameters
# number of frames for training, -1 uses all frames
num_frames: -1
# plot images
debug: False
# normalize/scale the difference with corresponding range value
normalize: True
# use the last n frame to calculate the difference image
num_last_ns: [1,2,3,4,5,6,7,8]

# Inputs
# the folder of raw LiDAR scans
data_folder: '../data/sequences/'
sequences: '08'

scan_folder: 'velodyne'
# ground truth poses file
pose_file: 'poses.txt'
# calibration file
calib_file: 'calib.txt'

# Outputs
# the suffix should be the same as num_last_n!
#residual_image_folder: '../data/sequences/08/residual_images_3'
visualize: True
#visualization_folder: '../data/sequences/08/residual_visualization_3'

# range image parameters
range_image:
  height: 64
  width: 2048
  fov_up: 3.0
  fov_down: -25.0
  max_range: 50.0
  min_range: 2.0

