# This file is covered by the LICENSE file in the root of this project.
# Developed by: Xieyuanli Chen
# Configuration for preparing residual images (specifying all the paths)
# --------------------------------------------------------------------

# General parameters
# number of frames for training, -1 uses all frames

debug: False

# Inputs
path_folder: '../data/path'
# the folder of training
train_folder: '../data/path/train_path'
# the folder of validation
valid_folder: '../data/path/valid_path'
# the folder of testing
test_folder: '../data/path/test_path'

# ground truth poses file
pose_file: '../data/sequences/08/poses.txt'
# calibration file
calib_file: '../data/sequences/08/calib.txt'

# Outputs
# the onehot encoded mask: 0,1,2
mask_image_folder: '../data/sequences/08/mask_image'

visualization_folder: '../data/sequences/08/mask_visualization'

# range image parameters
range_image:
  height: 64
  width: 2048
  fov_up: 3.0
  fov_down: -25.0
  max_range: 50.0
  min_range: 2.0

