# This file is covered by the LICENSE file in the root of this project.
# Developed by: Xieyuanli Chen
# Configuration for preparing residual images (specifying all the paths)
# --------------------------------------------------------------------

# General parameters
# number of frames for training, -1 uses all frames

debug: False

# Inputs
# the folder of raw LiDAR scans

data_folder: '/home/ak209/Desktop/hwei/AutoDrive/data/dataset/sequences'
sequences: ['06', '07', '08', '09', '10']


scan_folder: 'velodyne'
# ground truth poses file
pose_file: 'poses.txt'
# calibration file
calib_file: 'calib.txt'
# label folder
label_folder: 'labels'

# Outputs
# the onehot encoded mask: 0,1,2

mask_image_folder: 'mask_image'
visualize: True
visualization_folder: 'mask_visualization'



# range image parameters
range_image:
  height: 64
  width: 2048
  fov_up: 3.0
  fov_down: -25.0
  max_range: 50.0
  min_range: 2.0

